[package]
name = "rush"
version = "0.1.1"
edition = "2024"

[features]
default = ["tui"]
tui = ["ratatui", "crossterm", "arboard"]
dsa = ["tui"]

[dependencies]
pathsearch = "0.2.0"
regex = "1.12.3"
rustyline = "18.0.0"
shell-words = "1.1.1"
rand = "0.8"
ratatui = { version = "0.30", features = ["crossterm"], optional = true }
crossterm = { version = "0.28", optional = true }
arboard = { version = "3.4", optional = true }
